runtime: java11
instance_class: F2
automatic_scaling:
#  max_instances: 50
  max_concurrent_requests: 10
#  target_cpu_utilization: 0.8

entrypoint: 'java -cp "*" com.example.appengine.demo.jettymain.Main appengine-ski-1.0-SNAPSHOT.war'